### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ellisonleao** [HaitaoBio/magictools-ch#1]
Hey @HaitaoBio would you consider maintaining the chinese translation on the original repo? I think it would be easier to follow up with new inserts and we could also add a script to create the translation when new changes are added.

Let me know what you think.

**Comment by HaitaoBio** [comment]
No problem, so i should add the Chinese translation into the original repo and do PR?

**Comment by ellisonleao** [comment]
Yes, pretty much it :)
